package com.unihannover.gamedev.models;

public class Configuration {
    private String name;
    private String collectorId;
    private String token;
    private String mainApiUrl;
    private String jwtSecret;
    private String jiraIssueTypeIdEpic;
    private String jiraIssueTypeIdStory;
    private String jiraIssueTypeIdSubtask;

    public Configuration() {
    }

    // *** Autogenerated Setters & Getters ***

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCollectorId() {
        return collectorId;
    }

    public void setCollectorId(String collectorId) {
        this.collectorId = collectorId;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getMainApiUrl() {
        return mainApiUrl;
    }

    public void setMainApiUrl(String mainApiUrl) {
        this.mainApiUrl = mainApiUrl;
    }

    public String getJwtSecret() {
        return jwtSecret;
    }

    public void setJwtSecret(String jwtSecret) {
        this.jwtSecret = jwtSecret;
    }

    public String getJiraIssueTypeIdEpic() {
        return jiraIssueTypeIdEpic;
    }

    public void setJiraIssueTypeIdEpic(String jiraIssueTypeIdEpic) {
        this.jiraIssueTypeIdEpic = jiraIssueTypeIdEpic;
    }

    public String getJiraIssueTypeIdStory() {
        return jiraIssueTypeIdStory;
    }

    public void setJiraIssueTypeIdStory(String jiraIssueTypeIdStory) {
        this.jiraIssueTypeIdStory = jiraIssueTypeIdStory;
    }

    public String getJiraIssueTypeIdSubtask() {
        return jiraIssueTypeIdSubtask;
    }

    public void setJiraIssueTypeIdSubtask(String jiraIssueTypeIdSubtask) {
        this.jiraIssueTypeIdSubtask = jiraIssueTypeIdSubtask;
    }
}
