package com.unihannover.gamedev.models;

import javax.persistence.*;

@Entity
@Table(name = "JiraCollector_Metrics", schema="metrics")
public class Metric {

    /**
     * Events
     */
    public static final String EVENT_ISSUE_CREATED = "issue-created";
    public static final String EVENT_ISSUE_DELETED = "issue-deleted";
    public static final String EVENT_ISSUE_UPDATED = "issue-updated";

    /**
     * Actions
     */
    public static final String ACTION_NONE = "";
    public static final String ACTION_ISSUE_DONE = "issue-done";
    public static final String ACTION_ISSUE_ASSIGNED_AWAY = "issue-assigned-away";
    public static final String ACTION_ISSUE_ASSIGNED_TO_ME = "issue-assigned-to-me";
    public static final String ACTION_ISSUE_COMMENTED = "issue-commented";
    public static final String ACTION_ISSUE_COMMENT_EDITED = "issue-comment-edited";

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy=GenerationType.AUTO)
    private long id;

    @Column(name = "user_email")
    private String userEmail;

    @Column(name = "issue_key")
    private String issueKey;

    @Column(name = "event")
    private String eventType;

    @Column(name = "action")
    private String action;

    @Column(name = "timestamp")
    private String timestamp;

    // *** Autogenerated Setters & Getters ***

    public Metric(String userEmail, String issueKey, String eventType, String action, String timestamp) {
        this.userEmail = userEmail;
        this.issueKey = issueKey;
        this.eventType = eventType;
        this.action = action;
        this.timestamp = timestamp;
    }
}
