package com.unihannover.gamedev.models;

import javax.persistence.*;

@Entity
@Table(name = "JiraCollector_Metrics", schema = "metrics")
public class Metric {

    /**
     * Events
     */
    public static final String EVENT_ISSUE_CREATED = "issue-created";
    public static final String EVENT_ISSUE_DELETED = "issue-deleted";
    public static final String EVENT_ISSUE_UPDATED = "issue-updated";

    /**
     * Actions
     */
    public static final String ACTION_NONE = "";
    public static final String ACTION_ISSUE_DONE = "issue-done";
    public static final String ACTION_ISSUE_ASSIGNED_AWAY = "issue-assigned-away";
    public static final String ACTION_ISSUE_ASSIGNED_TO_ME = "issue-assigned-to-me";
    public static final String ACTION_ISSUE_COMMENTED = "issue-commented";
    public static final String ACTION_ISSUE_COMMENT_EDITED = "issue-comment-edited";

    /**
     * Issue types
     */
    public static final String ISSUE_TYPE_UNKNOWN = "";
    public static final String ISSUE_TYPE_EPIC = "epic";
    public static final String ISSUE_TYPE_STORY = "story";
    public static final String ISSUE_TYPE_SUBTASK = "subtask";

    /**
     * Auto-generated Id, we do not bother it
     */
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    /**
     * The (Jira's) user email address.
     */
    @Column(name = "user_email")
    private String userEmail;

    /**
     * The JIRA key of the affected issue
     */
    @Column(name = "issue_key")
    private String issueKey;

    /**
     * The type of the affected issue;
     * depends on the workflow, may be user-defined.
     * Predefined by Jira are e.g. "Story", "Epic"
     */
    @Column(name = "issue_type")
    private String issueType;

    /**
     * The event, e.g. issue created or issue updated
     */
    @Column(name = "event")
    private String eventType;

    /**
     * The action
     * More detailed information about the performed action, abstracted.
     * One of the ACTION_ constants
     */
    @Column(name = "action")
    private String action;

    /**
     * The timestamp when the action was performed
     */
    @Column(name = "timestamp")
    private String timestamp;

    // *** Autogenerated Setters & Getters ***

    public Metric(String userEmail, String issueKey, String issueType, String eventType, String action, String timestamp) {
        this.userEmail = userEmail;
        this.issueKey = issueKey;
        this.issueType = issueType;
        this.eventType = eventType;
        this.action = action;
        this.timestamp = timestamp;
    }
}
