package com.unihannover.gamedev.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import java.sql.Timestamp;
import java.io.Serializable;

/**
 * Represents an achievement achieved by a user
 */
public class UserAchievement implements Model{

	public UserAchievement(){
		super();
	}

    @Override
	public String toJSON()
	{
		StringBuilder json = new StringBuilder();
		json.append("{");
		json.append("\"achievementId\":  " + "\"" + achievementId + "\"" + ",");
		json.append("\"collectorId\":  " + "\"" + collectorId + "\"" + ",");
		json.append("\"progress\": " + "\"" + progress + "\"" + ",");
		json.append("\"userEmail\": " + "\"" + userEmail + "\"");
		json.append("}");
		return json.toString();
	}

	/**
	 * Required for composite primary keys
	 */
	public static class UserAchievementPK implements Serializable {
		protected String achievementId;
		protected String collectorId;
		protected String userEmail;

		public UserAchievementPK() {}

		public UserAchievementPK(String achievementId, String collectorId, String userEmail) {
			this.achievementId = achievementId;
			this.collectorId = collectorId;
			this.userEmail = userEmail;
		}

		// equals, hashCode ?!
	}

	private String achievementId;
	private String collectorId;
	private String userEmail;
	private float progress;
	private Timestamp lastUpdated;

	// *** Autogenerated Setters & Getters ***

	public String getAchievementId() {
		return achievementId;
	}

	public void setAchievementId(String achievementId) {
		this.achievementId = achievementId;
	}

	public String getCollectorId() {
		return collectorId;
	}

	public void setCollectorId(String collectorId) {
		this.collectorId = collectorId;
	}

	public String getUserEmail() {
		return userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public float getProgress() {
		return progress;
	}

	public void setProgress(float progress) {
		this.progress = progress;
	}

	public Timestamp getLastUpdated() {
		return lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
}
