stages:
  - build-and-test

main-build-and-test:
  stage: build-and-test
  script:
    - docker build -t registry.se.uni-hannover.de/swp1920/gamedev-1 ./main
    - docker run --rm registry.se.uni-hannover.de/swp1920/gamedev-1 mvn clean test
