version: '3.3'
#
# Suggestion for port conventions:
#  - 80   : Frontend
#  - 80xx : Development (pgAdmin, ...)
#  - 90xx : Connectors (WebHooks)
#
services:

  # The database
  db:
    image: postgres
    container_name: devgame_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devgame
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
# TODO: Volume für Datenbank-Dateien-> persistent ggü. Neustart

  # Administration tool for debug purposes
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: devgame_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8001:80
# TODO: Volume für Dateien -> Konfiguration der Datenbank-Verbindung nicht jedes mal notwendig

  # Main
  main:
    container_name: devgame_main
    restart: always
    build:
      context: ./main
    ports:
      - 8082:8080

  # A first test connector
  test-connector:
    container_name: devgame_test-connector
    restart: always
    build:
      context: ./test-connector
    ports:
      - 9001:80
    depends_on:
      - "db"

networks:
  default:
    driver: bridge
