version: '3.7'

#
# Services useful for debug purposes
#
# TODO: Port conventions

services:

  # Database administration tool (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: devgame_pgadmin
    restart: always
    environment:
      # Credentials for logging in into the pgadmin web-interface
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8001:80
    volumes:
      # Used for pre-configuring the connection to the main database; password 'root' still has to be entered
      - ./db.dev/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - devgame

  # LDAP-server (OpenLDAP)
  ldap-server:
    container_name: devgame_ldap-server
    image: osixia/openldap:1.3.0
    command: --copy-service --loglevel debug
    volumes:
      - ./main.dev/ldap/init:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro
    networks:
      - devgame

  # LDAP administration tool (phpLDAPadmin)
  ldap-admin:
    container_name: devgame_ldap-admin
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-server
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - 8002:80
    networks:
      - devgame
