version: '3'

services:
  bitbucket:
    image: eugenmayer/bitbucket
    depends_on:
      - db
    volumes:
      - bitbucketdata:/var/atlassian/bitbucket
    ports:
      - '7990:7990'
    environment:
      - 'BITBUCKET_PROXY_NAME='
      - 'BITBUCKET_PROXY_PORT='
      - 'BITBUCKET_PROXY_SCHEME='
      - 'BITBUCKET_DELAYED_START='
      - 'DOCKER_WAIT_HOST=db'
      - 'DOCKER_WAIT_PORT=5432'

  db:
    image: postgres:11
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=bitbucketdb'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=bitbucketdb'
      - 'POSTGRES_ENCODING=UTF8'

volumes:
  bitbucketdata:
    external: false
  postgresqldata:
    external: false
    
networks:
  default:
    external:
      name: devgame-network