package com.unihannover.gamedev.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import java.io.Serializable;

/**
 * Represents an achievement
 */
@Entity
@IdClass(Achievement.AchievementPK.class)
@Table(name = "achievements", schema = "main")
public class Achievement {

	/**
	 * Required for composite primary keys
	 */
	public static class AchievementPK implements Serializable {
		protected String id;
		protected String collectorId;

		public AchievementPK() {}

		public AchievementPK(String id, String collectorId) {
			this.id = id;
			this.collectorId = collectorId;
		}

		// equals, hashCode ?!
	}

    @Id
    @Column(name = "id")
    private String id;

	@Id
	@Column(name = "collector_id")
    private String collectorId;

    @Column(name = "name")
    private String name;

    @Column(name = "description")
    private String description;

    @Column(name = "value")
    private float value;

	// *** Autogenerated Setters & Getters ***

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCollectorId() {
		return collectorId;
	}

	public void setCollectorId(String collectorId) {
		this.collectorId = collectorId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public float getValue() {
		return value;
	}

	public void setValue(float value) {
		this.value = value;
	}
}
