package com.unihannover.gamedev.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Represents a User, using the E-Mail adress as pimary key.
 */
@Entity
@Table(name = "users", schema = "main")
public class User {

	@Id
	@Column(name = "email")
	private String email;

	@Column(name = "uid")
	private String uid;

	@Column(name = "username")
	private String userName;

	@Column(name = "fullname")
	private String fullName;

	@Column(name = "anonymous")
	private boolean anonymous;

	@Column(name = "level")
	private float level;

	@Column(name = "score")
	private float score;

	// *** Autogenerated Setters & Getters ***

	/**
	 * Returns the E-Mail adrees (primary key) of a User.
	 *
	 * @return The mail adress
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * Sets the E-Mail adress of a user to a given adress.
	 * The E-Mail adress is the primary key.
	 *
	 * @param email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Returns the id of the User.
	 * The uid is mostly redundant because the E-Mail adress is enough to identify Users.
	 *
	 * @return The uid
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * Sets the id of the User.
	 * The uid is mostly redundant because the E-Mail adress is enough to identify Users.
	 *
	 * @param uid The uid
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * Returns the name of the User.
	 *
	 * @return The user name
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * Sets the name of the User to a given value.
	 *
	 * @param userName The new user name
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * Returns the Full name of a user.
	 *
	 * @return The full name of the user
	 */
	public String getFullName() {
		return fullName;
	}

	/**
	 * Sets the full name of the user.
	 * The Full name is in the format: firstname lastname
	 *
	 * @param fullName The full name of the user
	 */
	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	/**
	 * Represents the "hidden"-status of the user.
	 * If a User is anonymous, the user will not be shown in the ranking list.
	 *
	 * @return True if the User is anonymous
	 */
	public boolean isAnonymous() {
		return anonymous;
	}

	/**
	 * Sets the "hidden"-status of the user.
	 * If a User is anonymous, the user will not be shown in the ranking list.
	 *
	 * @param anonymous True if the User is anonymous
	 */
	public void setAnonymous(boolean anonymous) {
		this.anonymous = anonymous;
	}

	/**
	 * Represents the User with a String.
	 * If the String starts with "*", the user is anonymous.
	 *
	 * @return
	 */
	public String toString() {
		String s = "";
		if(this.anonymous) {
			s = "*";
		}
		s += this.userName + " (" + this.fullName + ") ";
		return s;
	}

	/**
	 * Returns the level of the User.
	 *
	 * @return The user level
	 */
	public float getLevel() {
		return level;
	}

	/**
	 * Sets the level of the user to a given value.
	 *
	 * @param level The new user level
	 */
	public void setLevel(float level) {
		this.level = level;
	}

	/**
	 * Returns the score of the User.
	 *
	 * @return The user score
	 */
	public float getScore() {
		return score;
	}

	/**
	 * Sets the score of the User to a givan value.
	 *
	 * @param score The user score
	 */
	public void setScore(float score) {
		this.score = score;
	}
}
