package com.unihannover.gamedev.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Represents a user
 */
@Entity
@Table(name = "users", schema = "main")
public class User {

	@Id
	@Column(name = "email")
	private String email;

	@Column(name = "uid")
	private String uid;

	@Column(name = "username")
	private String userName;

	@Column(name = "fullname")
	private String fullName;

	@Column(name = "anonymous")
	private boolean anonymous;

	@Column(name = "level")
	private float level;

	@Column(name = "score")
	private float score;

	// *** Autogenerated Setters & Getters ***

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public boolean isAnonymous() {
		return anonymous;
	}

	public void setAnonymous(boolean anonymous) {
		this.anonymous = anonymous;
	}

	public String toString() {
		String s = "";
		if(this.anonymous) {
			s = "*";
		}
		return s += this.userName + "(" + this.lastName + ", " this.firstName + ") ";
	}
	

	public float getLevel() {
		return level;
	}

	public void setLevel(float level) {
		this.level = level;
	}

	public float getScore() {
		return score;
	}

	public void setScore(float score) {
		this.score = score;
	}
}
