package com.unihannover.gamedev.models;

import javax.persistence.*;
import java.io.Serializable;


@Entity
@IdClass(UserAchievement.UserAchievementPK.class)
@Table(name = "user_achievements", schema = "main")
public class UserAchievementWOT {

    public static class UserAchievementPK implements Serializable {
        protected String achievementId;
        protected String collectorId;
        protected String userEmail;

        public UserAchievementPK() {}

        public UserAchievementPK(String achievementId, String collectorId, String userEmail) {
            this.achievementId = achievementId;
            this.collectorId = collectorId;
            this.userEmail = userEmail;
        }

        // equals, hashCode ?!
    }

    @Id
    @Column(name = "achievement_id")
    private String achievementId;

    @Id
    @Column(name = "collector_id")
    private String collectorId;

    @Id
    @Column(name = "user_email")
    private String userEmail;

    @Column(name = "progress")
    private double progress;



    // *** Autogenerated Setters & Getters ***

    public String getAchievementId() {
        return achievementId;
    }

    public void setAchievementId(String achievementId) {
        this.achievementId = achievementId;
    }

    public String getCollectorId() {
        return collectorId;
    }

    public void setCollectorId(String collectorId) {
        this.collectorId = collectorId;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public flodoubleat getProgress() {
        return progress;
    }

    public void setProgress(double progress) {
        this.progress = progress;
    }
}
