package com.unihannover.gamedev.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import java.io.Serializable;

/**
 * Represents an achievement
 */
public class Achievement implements Model{

	/**
	 * Required for composite primary keys
	 */
	public static class AchievementPK implements Serializable {
		protected String id;
		protected String collectorId;

		public AchievementPK() {}

		public AchievementPK(String id, String collectorId) {
			this.id = id;
			this.collectorId = collectorId;
		}

		// equals, hashCode ?!
	}

    private String id = "";
    private String collectorId = "0";
    private String name = "TestAchievement";
    private String description = "Simple test achievement";
    private float value = 0;

	// *** Autogenerated Setters & Getters ***

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCollectorId() {
		return collectorId;
	}

	public void setCollectorId(String collectorId) {
		this.collectorId = collectorId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public float getValue() {
		return value;
	}

	public void setValue(float value) {
		this.value = value;
	}



	public String toJSON()
	{
		StringBuilder json = new StringBuilder();
		json.append("{");
		json.append("\"collectorId\": " + " " + collectorId + ",");
		json.append("\"description\": " + " " + "\"" + description + "\"" + ",");
		json.append("\"name\": " + "\"" + name + "\"" + ",");
		json.append("\"value\": " + value);
		json.append("}");
		return json.toString();
	}

}
