package com.unihannover.gamedev.models;

import javax.persistence.*;

@Entity
@Table(name = "GenerellCollector_Metrics", schema="metrics")
public class Metric {

   

    /**
     * Auto-generated Id, we do not bother it
     */
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy=GenerationType.AUTO)
    private long id;

    /**
     * The user email address.
     */
    @Column(name = "user_email")
    private String userEmail;


    // *** Autogenerated Setters & Getters ***

    public Metric(String userEmail) {
        this.userEmail = userEmail;
       // ...
    }
}
