package com.unihannover.gamedev.models;

public class Configuration {
	private String name;
	private String collectorId;
    private String token;
    private String mainApiUrl;
    private String jwtSecret;
	
    
    public Configuration() {}

	// *** Autogenerated Setters & Getters ***

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCollectorId() {
		return collectorId;
	}

	public void setCollectorId(String collectorId) {
		this.collectorId = collectorId;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getMainApiUrl() {
		return mainApiUrl;
	}

	public void setMainApiUrl(String mainApiUrl) {
		this.mainApiUrl = mainApiUrl;
	}

	public String getJwtSecret() {
		return jwtSecret;
	}

	public void setJwtSecret(String jwtSecret) {
		this.jwtSecret = jwtSecret;
	}
}
