package com.unihannover.gamedev.models;

public class ConfigurationTest {


    // *** Autogenerated Setters & Getters ***

    @Test
    public void testSetAndGetName(){
        Configuration test = new Configuration();
        test.setName("Conf 1");
        assertEquals("Conf 1", test.getName());
    }

    @Test
    public void testSetAndGetCollectorId(){
        Configuration test = new Configuration();
        test.setCollectorId("Col 1");
        assertEquals("Col 1", test.getCollectorId());
    }

    @Test
    public void testSetAndGetToken(){
        Configuration test = new Configuration();
        test.setToken("Some Token");
        assertEquals("Some Token", test.getToken());
    }

    @Test
    public void testSetAndGetMainApiUrl(){
        Configuration test = new Configuration();
        test.setMainApiUrl("mostawesomeurlever.com");
        assertEquals("mostawesomeurlever.com", test.getMainApiUrl());
    }


    @Test
    public void testSetAndGetSecret(){
        Configuration test = new Configuration();
        test.setJwtSecret("Some Secret");
        assertEquals("Some Secret", test.getJwtSecret());
    }

    @Test
    public void testSetAndGetEpic(){
        Configuration test = new Configuration();
        test.setJiraIssueTypeIdEpic("Epic");
        assertEquals("Epic", test.getJiraIssueTypeIdEpic());
    }

    @Test
    public void testSetAndGetStory(){
        Configuration test = new Configuration();
        test.setJiraIssueTypeIdStory("Story");
        assertEquals("Story", test.getJiraIssueTypeIdStory());
    }

    @Test
    public void testSetAndGetSubtask(){
        Configuration test = new Configuration();
        test.setJiraIssueTypeIdSubtask("Subtask");
        assertEquals("Subtask", test.getJiraIssueTypeIdSubtask());
    }
}
