package com.unihannover.gamedev.models;

/**
 * Represents a user
 */
public class UserTest {
    private String email;
    private String uid;
    private String userName;
    private String fullName;
    private boolean anonymous;
    private float level;
    private float score;

    // *** Autogenerated Setters & Getters ***

    @Test
    public void testSetAndGetEmail(){
        Configuration test = new Configuration();
        test.setEmail("test@mail.com");
        assertEquals("test@mail.com", test.getEmail());
    }

    @Test
    public void testSetAndGetUid(){
        Configuration test = new Configuration();
        test.setUid("111");
        assertEquals("111", test.getUid());
    }

    @Test
    public void testSetAndGetUserName(){
        Configuration test = new Configuration();
        test.setUserName("Testuser");
        assertEquals("Testuser", test.getUserName());
    }

    @Test
    public void testSetAndGetFullName(){
        Configuration test = new Configuration();
        test.setFullName("Max Meier");
        assertEquals("Max Meier", test.getFullName());
    }

    @Test
    public void testSetAndGetAnonymousToTrue(){
        Configuration test = new Configuration();
        test.setAnonymous(true);
        assertEquals(true, test.getAnonymous());
    }

    @Test
    public void testSetAndGetAnonymousToFalse(){
        Configuration test = new Configuration();
        test.setAnonymous(false);
        assertEquals(false, test.getAnonymous());
    }

    @Test
    public void testSetAndGetLevel(){
        Configuration test = new Configuration();
        test.setLevel(1);
        assertEquals(1, test.getLevel());
    }

    @Test
    public void testSetAndGetScore(){
        Configuration test = new Configuration();
        test.setScore(1);
        assertEquals(1, test.getScore());
    }

    /*
    public String toJSON() {

    }
    */
     */
}
