package com.unihannover.gamedev.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.sql.Timestamp;

/**
 * Represents a collector, that contains data used to determine Achievement progress.
 */
@Entity
@Table(name = "collectors", schema = "main")
public class Collector {

    public Collector(){}
    public Collector(CollectorWOT cWOT){
        this.id = cWOT.getId();
        this.name = cWOT.getName();
        this.token = cWOT.getToken();
        this.lastSeen = new Timestamp(System.currentTimeMillis());
    }
    @Id
    @Column(name = "id")
    private String id;

    @Column(name = "name")
    private String name;

    @Column(name = "last_seen")
    private Timestamp lastSeen;

    @Column(name = "token")
    @JsonIgnore
    private String token;

    // *** Autogenerated Setters & Getters ***

    /**
     * Returns the id of a collector (primary key).
     *
     * @return The collector id
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the id of a collector.
     * Usually only used to initialise the collector, since id is a primary key.
     *
     * @param id The id of a collector
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Returns the collector name.
     *
     * @return The name of the collector
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the collector to a given value.
     *
     * @param name The new collector name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the latest time, the collector was notices active.
     *
     * @return The timestamp
     */
    public Timestamp getLastSeen() {
        return lastSeen;
    }

    /**
     * Sets the latest time, the collector was notices active.
     * Mostly used to set the timestamp to the time this function is called.
     *
     * @param lastSeen The new time
     */
    public void setLastSeen(Timestamp lastSeen) {
        this.lastSeen = lastSeen;
    }

    /**
     * Returns a Token used to verify access.
     *
     * @return The token
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets a token to verify access.
     *
     * @param token The token
     */
    public void setToken(String token) {
        this.token = token;
    }
}
